---
- name: create a security group 
  hosts: all
  remote_user: root
  vars:
#vars auth openstack
    ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python3.6"
    OS_USERNAME: "admin"
    OS_PASSWORD: "b6bb4b7857fa4119"
    OS_REGION_NAME: "RegionOne"
    OS_AUTH_URL: "http://172.25.52.127:5000/v3"
    OS_USER_DOMAIN_NAME: "Default"
    OS_PROJECT_DOMAIN_NAME: "Default"
    PS1: '[\u@\h \W(keystone_admin)]\$'
    OS_PROJECT_NAME: "admin"
    OS_PROJECT: "{{ project | default(None) }}"
#vars security_group
    SECURITY_GROUP: "{{ sec_group | default(None) }}"
    PROTOCOL: "tcp"
  tasks:
    - debug: var=ansible_host  
    - name: Create a security group
      os_security_group:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        name: "{{ SECURITY_GROUP }}"
        project: "{{ OS_PROJECT }}"

    - name: Create a security group rule
      os_security_group_rule:
        state: present
        auth:
          auth_url: "{{ OS_AUTH_URL }}"
          username: "{{ OS_USERNAME }}"
          password: "{{ OS_PASSWORD }}"
          project_name: "{{ OS_PROJECT_NAME }}"
          os_user_domain_name: "{{ OS_USER_DOMAIN_NAME }}"
          os_project_domain_name: "{{ OS_PROJECT_DOMAIN_NAME }}"
        security_group: "{{ SECURITY_GROUP }}"
        protocol: "{{ PROTOCOL }}"
        remote_ip_prefix: 0.0.0.0/0
        project: "{{ OS_PROJECT }}"    
